server:
  port: 8080

spring:
  application:
    name: entra-id-sso
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID:your-client-id}
            client-secret: ${AZURE_CLIENT_SECRET:your-client-secret}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Microsoft
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:your-tenant-id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:your-tenant-id}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:your-tenant-id}/discovery/v2.0/keys
            user-name-attribute: sub

# Microsoft Graph Configuration
microsoft:
  graph:
    tenant-id: ${AZURE_TENANT_ID:your-tenant-id}
    client-id: ${AZURE_CLIENT_ID:your-client-id}
    client-secret: ${AZURE_CLIENT_SECRET:your-client-secret}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG 